#!/usr/bin/python

import os, sys

CXXfiles = [ f for f in os.listdir(".") if f.endswith(".cc") ]
Hfiles   = [ f for f in os.listdir(".") if f.endswith(".hh")  ]

def fix(f,extension):

    suff = extension
    newfile = f.split(".")[0] + ".{}".format(extension)

    print f,newfile
    os.system("cp %s %s" % (f,newfile));
    #os.system("sed -i '' -e 's/%s/%s/g' %s" % (pre,n,newfile) );
    #os.system("sed -i '' -e 's/%s/%s/g' %s" % (pre.upper(),n.upper(),newfile) );
    os.system("sed -i '' -e 's/larlight/larlite/g' %s" % (newfile) );
    os.system("sed -i '' -e 's/.hh/.h/g' %s" % (newfile) );
    os.system("sed -i '' -e 's/_CC/_CXX/g' %s" % (newfile) );
    os.system("sed -i '' -e 's/_HH/_H/g' %s" % (newfile) );


for f in CXXfiles:
    fix(f,"cxx")

for f in Hfiles:
    fix(f,"h")

